services:
  localstack:
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
      - AWS_DEFAULT_REGION=us-east-2
      - DEBUG=1
    volumes:
      - ./.docker/localstack/bootstrap.sh:/etc/localstack/init/ready.d/01-bootstrap.sh
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - video-processor-network
    healthcheck:
      test: ["CMD", "awslocal", "sqs", "list-queues"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - GO_ENV=development
      - API_PORT=8080
      - API_HOST=0.0.0.0
      - AWS_REGION=us-east-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_SQS_FRAME_EXTRACTION_QUEUE=http://localstack:4566/000000000000/frame-extraction-queue
      - S3_BUCKET_NAME=video-frames-bucket
    networks:
      - video-processor-network
    restart: unless-stopped

networks:
  video-processor-network:
    driver: bridge
